config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :subscriptions

  devise_for :users, controllers: { registrations: "registrations" }

  root 'pages#home'

  get '/signup', to: 'pages#signup', as: 'signup'

  get '/training', to: 'pages#training', as: 'training'

  get '/users/sign_up' => 'registrations#new'

  get '/contact', to: 'pages#contact', as: 'contact'

  get '/player', to: 'pages#player', as: 'player'

  get '/gameart', to: 'pages#game_art', as: 'gameart'

end

app/views/pages/contact.html.erb
<!-- wrapper -->
<div class="rapidxwpr">

  <!-- page -->
  <div class="page">

    <!-- contact page -->
    <div class="contact_page">

      <div class="contact_section">
        <div class="contact_section_cont">
          <h3>We are always here to help</h3>
          <p>Questions? Comments? Just want to tell us you love us?</p>
          <form action="" method="post">
            <ul>
              <li><input type="text" name="" class="contact-field" value="" placeholder="Name" /></li>
              <li><input type="text" name="" class="contact-field" value="" placeholder="Email" /></li>
              <li><textarea name="" class="contact-field" placeholder="Message"></textarea></li>
              <li><input type="submit" name="" class="contact-btn" value="SEND" /></li>
            </ul>
          </form>
          <div class="call-us">
            <span class="title">Or call us at</span>
            <span class="numbers">305-733-7260</span>
          </div>
        </div>
        <img src="images/animated_tree.gif" alt="" class="contact-section-img" />
      </div>

      <div class="faq_section">
        <h3>Frequently asked questions</h3>
        <ul>
          <li><a href="">what skill level or age do students need to be?</a></li>
          <li><a href="">What software and tools will I be learning?</a></li>
          <li><a href="">Do I get a diploma or certificate?</a></li>
          <li><a href="">What type of computer do I need?</a></li>
          <li><a href="">What can I actually do once I am do with my training?</a></li>
        </ul>
      </div>

    </div>
    <!-- / contact page -->

  </div>
  <!-- / page -->



</div>
<!-- / wrapper -->


app/views/pages/game_art.html.erb
 <!-- main image -->
  <div class="main-image">
    <img src="images/art-banner.jpg" alt="" />
  </div>
  <!-- / main image -->

  <!-- page -->
  <div class="page">

    <div class="art_page_intro1">
      <h2>Game Art from the Pros!</h2>
      <p>We love our studnets! Which is why we work so hard to provide the most real world learning enviroment we can. This is why we are building the worlds largest game art library. And the best part is these amazing art assets produced by verterans in the game industry will always be free for our studnets to use while training with us, or even in their own games and projects royalty free!</p>
    </div>
    
    <div class="art_page_intro2">
      <h3>More then just game art, Go behind the scenes</h3>
      <p>It’s our mission to provide the most real world learning enviroment we can for our students. This is why our game art packs are much more then a collection of great art , they also introduce students to the production process as we often included concept sketches and early mockup.</p>
      <img src="images/art-intro-img2.png" class="art-intro-img2" alt="" />
    </div>
    
    <div class="art_packs_list">
      <div class="art_packs_title">
        <h1>GAME ART PACKS</h1>
      </div>
      <div class="art_pack_box">
        <h3>The lost world</h3>
        <img src="images/art-pack-img1.jpg" alt="" />
        <div class="art_pack_access">
          <div class="art_pack_download"><a href="">Always FREE FOR STUDNETS<em>download now</em></a></div>
          <div class="art_pack_buy"><a href="" class="buy-btn">Buy Now<em>instant download</em></a>non-STUDNETS<br />$79.95</div>
        </div>
      </div>
      <div class="art_pack_box">
        <h3>Frump saves the world</h3>
        <img src="images/art-pack-img2.jpg" alt="" />
        <div class="art_pack_access">
          <div class="art_pack_download"><a href="">Always FREE FOR STUDNETS<em>download now</em></a></div>
          <div class="art_pack_buy"><a href="" class="buy-btn">Buy Now<em>instant download</em></a>non-STUDNETS<br />$89.95</div>
        </div>
      </div>
      <div class="art_pack_box">
        <h3>Poly pastel platformer</h3>
        <img src="images/polyartpack.jpg" alt="" />
        <div class="art_pack_access">
          <div class="art_pack_download"><a href="">Always FREE FOR STUDNETS<em>download now</em></a></div>
          <div class="art_pack_buy"><a href="" class="buy-btn">Buy Now<em>instant download</em></a>non-STUDNETS<br />$9.95</div>
        </div>
      </div>
    </div>

  </div>
  <!-- page -->

  <!-- footer -->
  <div id="footer">
    <div class="footer_menu">
      <ul>
        <li><a href="training.html">Training</a></li>
        <li><a href="">FAQ</a></li>
        <li><a href="student.html">Become a student</a></li>
        <li><a href="">Login</a></li>
      </ul>
      <ul>
        <li><a href="contact.html">Contact</a></li>
        <li><a href="">Blog</a></li>
        <li><a href="">Privacy</a></li>
        <li><a href="">Terms</a></li>
      </ul>
    </div>
    <div class="footer_share"><a href="mailto:?subject=Learn how to make video games &body=Hey check out the School of Interactive Design where I am learning how to make awesome games. www.schoolofinteractivedesign.com">Share with a friend</a></div>
    <div class="footer_social_links">
      <a href="https://twitter.com/SID_Report"><img src="images/icon-twitter.png" alt="" /></a>
      <a href="https://www.facebook.com/schoolofinteractivedesign"><img src="images/icon-facebook.png" alt="" /></a>
      <a href="https://instagram.com/school_of_interactive_design/"><img src="images/icon-instagram.png" alt="" /></a>
    </div>
  </div>
  <!-- / footer -->

</div>
<!-- / wrapper -->

<script type="text/javascript" src="js/jquery.min.js"></script>

app/views/pages/home1.html.erb
<div class="info">
				
	<div class="paragraph-header">
		<p>CREATE AMAZING GAMES</p>
	</div>
	
	<div class="paragraph">
		<p class="big">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi malesuada neque eu dolor gravida ornare. Pellentesque in ligula turpis. Cras blandit, dolor vel cursus convallis, ante metus dictum enim, eget eleifend massa metus venenatis diam. Maecenas at posuere libero, sit amet molestie nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam id pellentesque arcu, vel fringilla enim. Nullam a mi at lacus sollicitudin convallis. Etiam tempus laoreet ipsum, at laoreet tellus porta ac. Nunc sit amet congue risus.</p>
	</div>

	<div class="sign-up">
		<%= link_to image_tag('/images/signup.png'), new_user_registration_path %>
	</div>
	
	<div class="block-image">
		<img src="/images/3dblockimage.png"/>
	</div>
</div>

app/views/pages/player.html.erb
  <%= javascript_include_tag "bootstrap.min.js" %>
  <!-- page -->
  <div class="page">

    <!-- player page -->
    <div class="player_page">
      <div class="project_list">
        <span class="trigger-title">1. Project Description</span>
        <div class="trigger-box">
          This series of video tutorials is for those who are completely new to Unity 3D and want to get up and running quickly with the fundamental features of Unity. Each of these videos is design to teach you step by step the core basics of Unity so you can go on and learn from more advanced tutorials throughout the site.  Each of these videos is design to teach you step by step the core basics of Unity so you can go on and learn from more advanced tutorials throughout the site.
        </div>
        <span class="trigger-title">2. Project Files</span>
        <div class="trigger-box download-box">
          <p>Download project files</p>
          <a href=""><img src="images/download-img.jpg" alt="" /></a>
          <p>Secretagent.zip 22MB</p>
        </div>
        <span class="trigger-title">3. Chapters</span>
        <div class="trigger-box">
          <ul>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter01">Intro to unity3D</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter02">working with objects</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter03">Bulding the project</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter04">Lighting</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter05">Exporting shapes</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter06">Render settings</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter07">Adjusting each item</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter08">setting up particeles</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter09">Adding textures</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter10">Boss battle</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter11">Exporting shapes</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter12">Fading chanles together</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter13">Intro to unity3D</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter14">working with objects</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter15">Bulding the project</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter16">Lighting</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter17">Exporting shapes</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter18">Render settings</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter19">Adjusting each item</a></li>
            <li><a href="javascript:void(0);" class="chapterlink" id="chapter20">setting up particeles</a></li>
          </ul>
        </div>
      </div>
      <% if !user_signed_in? %>
        <div class="videos" onclick="return false" data-toggle="modal" data-target="#myModal">
          <a href="#"><img src="/images/video_place_holder.jpg"/></a>
        </div>
        <div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-body">
                <%= render "devise/sessions/new" %>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div class="project_video">
          <iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
      <% end %>
    </div>
    <!-- / player page -->

  </div>
  <!-- / page -->

<script type="text/javascript">
  <!--
  $(document).ready(function() {
    function openFirstPanel(){
      $('div.project_list > span.trigger-title:first-child').addClass('active');
      $('div.project_list > span.trigger-title:first-child').next().addClass('active').slideDown();
    }
    var allPanels = $('div.project_list div.trigger-box').hide();
    var allTriggers = $('div.project_list span.trigger-title');
    openFirstPanel();
    $('div.project_list span.trigger-title').click(function() {
      allPanels.slideUp();
      allTriggers.removeClass('active');
      $(this).toggleClass('active').next().slideDown();
      return false;
    });
    var videolist = {
      chapter01: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter02: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter03: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter04: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter05: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter06: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter07: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter08: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter09: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter10: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter11: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter12: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter13: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter14: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter15: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter16: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter17: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter18: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter19: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
      chapter20: '<iframe src="http://player.vimeo.com/video/100902001?title=0&byline=0&portrait=0" width="742" height="417" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
    }
    $('.chapterlink').on('click',function(e){
       e.preventDefault();
       $('.project_video').html(videolist[this.id]);
    });
  });
  // -->
</script>

app/views/pages/training.html.erb
  <!-- main image -->
  <div class="main-image">
    <img src="images/slide-image4.jpg" alt="" />
  </div>
  <!-- / main image -->

  <!-- page -->
  <div class="page">

    <!-- page header -->
    <div class="page_header">
      <h2>Training portal</h2>
      <ul>
        <li><a href="#2d">2D game design</a></li>
        <li><a href="#3d">3D game design</a></li>
        <li><a href="#ca">computer animation</a></li>
        <li><a href="#dp">digital painting</a></li>
      </ul>
    </div>
    <!-- / page header -->

    <!-- banner -->
    <div class="banner">
      <a class="swipebox" rel="vimeo" href="http://vimeo.com/22439234"><img src="images/training-banner.jpg" alt="" /></a>
    </div>
    <!-- / banner -->

    <!-- page subheader -->
    <div class="page_subheader">
      And your training begins
    </div>
    <!-- / page subheader -->

    <!-- course list -->
    <div class="course_list" id="2d">
      <h4>2D Game design courses</h4>
      <div class="course_intro">
        Welcome to your training portal. Here you'll find in-depth training on 2D and 3D game design, computer animation, graphic design, and digital painting. If you are a new student and new to the digital arts, simply start with the very first training series. We take the time to lead students step by step through the basics all the way up to advanced industry techniques. But if you would like to focus more on one subject versus another, feel free to jump around and
      </div>
      <div class="course_box">
        <%= link_to player_path do %>
            <%= image_tag "/images/course01.jpg", alt: "" %>
            <span class="title">introduction to game design</span>
        <% end %>
      </div>
      <div class="course_box">
        <%= link_to player_path do %>
            <%= image_tag "/images/course02.jpg", alt: "" %>
            <span class="title">Working with 2d Physics</span>
        <% end %>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course03.jpg" alt="" /><span class="title">Creating a 2d platformer</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course04.jpg" alt="" /><span class="title">CREATING FLAPPY BIRD</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course05.jpg" alt="" /><span class="title">CREATING AN INDIE PLATFORMER</span></a>
      </div>
    </div>
    <!-- / course list -->

    <!-- course list -->
    <div class="course_list" id="3d">
      <h4>3D Game design</h4>
      <div class="course_intro">
        Welcome to your training portal. Here you'll find in-depth training on 2D and 3D game design, computer animation, graphic design, and digital painting. If you are a new student and new to the digital arts, simply start with the very first training series. We take the time to lead students step by step through the basics all the way up to advanced industry techniques. But if you would like to focus more on one subject versus another, feel free to jump around and
      </div>
      <div class="course_box">
        <a href=""><img src="images/course06.jpg" alt="" /><span class="title">Getting Started with Unity3D</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course07.jpg" alt="" /><span class="title">Introduction to coding in c#</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course08.jpg" alt="" /><span class="title">Mastering the Fundamentals</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course09.jpg" alt="" /><span class="title">Building Your First Level</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course10.jpg" alt="" /><span class="title">Creating a Boss Battle</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course11.jpg" alt="" /><span class="title">Working With Particles</span></a>
      </div>
    </div>
    <!-- / course list -->

    <!-- course list -->
    <div class="course_list" id="ca">
      <h4>Computer animation</h4>
      <div class="course_intro">
        Welcome to your training portal. Here you'll find in-depth training on 2D and 3D game design, computer animation, graphic design, and digital painting. If you are a new student and new to the digital arts, simply start with the very first training series. We take the time to lead students step by step through the basics all the way up to advanced industry techniques. But if you would like to focus more on one subject versus another, feel free to jump around and
      </div>
      <div class="course_box">
        <a href=""><img src="images/course12.jpg" alt="" /><span class="title">Introduction to Maya</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course13.jpg" alt="" /><span class="title">Introduction to Mudbox</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course14.jpg" alt="" /><span class="title">Introduction to 3D Studio Max</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course15.jpg" alt="" /><span class="title">Polygon Modeling 1 with 3D Studio Max</span></a>
      </div>
    </div>
    <!-- / course list -->

    <!-- course list -->
    <div class="course_list" id="dp">
      <h4>Graphic Design</h4>
      <div class="course_intro">
        Welcome to your training portal. Here you'll find in-depth training on 2D and 3D game design, computer animation, graphic design, and digital painting. If you are a new student and new to the digital arts, simply start with the very first training series. We take the time to lead students step by step through the basics all the way up to advanced industry techniques. But if you would like to focus more on one subject versus another, feel free to jump around and
      </div>
      <div class="course_box">
        <a href=""><img src="images/course16.jpg" alt="" /><span class="title">Introduction to Photoshop</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course17.jpg" alt="" /><span class="title">Pro Tips and Tricks</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course18.jpg" alt="" /><span class="title">Creating a Safari Compass</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course19.jpg" alt="" /><span class="title">Working With The Warp Tool</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course20.jpg" alt="" /><span class="title">Pop Out Effect</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course21.jpg" alt="" /><span class="title">Animation Basics</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course22.jpg" alt="" /><span class="title">Introduction to Illustrator</span></a>
      </div>
    </div>
    <!-- / course list -->

    <!-- course list -->
    <div class="course_list">
      <h4>Digital painting</h4>
      <div class="course_intro">
        Welcome to your training portal. Here you'll find in-depth training on 2D and 3D game design, computer animation, graphic design, and digital painting. If you are a new student and new to the digital arts, simply start with the very first training series. We take the time to lead students step by step through the basics all the way up to advanced industry techniques. But if you would like to focus more on one subject versus another, feel free to jump around and
      </div>
      <div class="course_box">
        <a href=""><img src="images/course23.jpg" alt="" /><span class="title">Introduction to Digital Painting</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course24.jpg" alt="" /><span class="title">Intermediate Digital Painting</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course25.jpg" alt="" /><span class="title">Creature Concept Design</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course26.jpg" alt="" /><span class="title">Advanced Character Painting</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course27.jpg" alt="" /><span class="title">Advanced Environment Design</span></a>
      </div>
      <div class="course_box">
        <a href=""><img src="images/course28.jpg" alt="" /><span class="title">Advanced Illustration</span></a>
      </div>
    </div>
    <!-- / course list -->

  </div>
  <!-- page -->

<script type="text/javascript">
  <!--
  $(document).ready(function() {
    $(".swipebox").swipebox();
  });
  // -->
</script>