config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :subscriptions

  devise_for :users, controllers: { registrations: "registrations" }

  root 'pages#home'

  get '/signup', to: 'pages#signup', as: 'signup'

  get '/training', to: 'pages#training', as: 'training'

  get '/users/sign_up' => 'registrations#new'

  get '/contact', to: 'pages#contact', as: 'contact'

  get '/player', to: 'pages#player', as: 'player'

  get '/gameart', to: 'pages#game_art', as: 'gameart'

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  include ActiveModel::Dirty
	belongs_to :user
	accepts_nested_attributes_for :user

	attr_accessor :card_number, :card_verification, :years

  # validate :validate_card, :on => :create
  
  before_update :set_year, :add_years, :a_thing
  before_create :purchase

	def purchase
    @response = GATEWAY.purchase(price_in_cents, credit_card, purchase_options)  
    @years = ""
    @response.success?
  end

  def set_year
    @years = years
  end

  def a_thing
    years_changed = self.sub_years_changed?
    purchase if years_changed
  end

  def error_message
    if @response != nil
      @response.params["Errors"]["LongMessage"]
    end
  end

  def add_years
    if (self.sub_years >= 1 && (@years != nil && @years != ""))
      self.sub_years += @years.to_i  
    end
  end
  
	def price_in_cents
    if @years == "" || @years == nil
      @years = 1
    end
    (1*100).round * @years.to_i 
	end

	private

	def purchase_options
    {
      :ip => ip_address,
      :billing_address => {
        :name     => first_name + " " + last_name,
        :city     => city,
        :state    => state,
        :country  => country,
        :zip      => postal_code
      }
    }
  end

	# def validate_card
 #    unless credit_card.valid?
 #      credit_card.errors.full_messages.each do |message|
 #        errors[:base] << message
 #      end
 #    end
 #  end
  
  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
      :brand               => card_type,
      :number             => card_number,
      :verification_value => card_verification,
      :month              => card_expires_on.month,
      :year               => card_expires_on.year,
      :first_name         => first_name,
      :last_name          => last_name
    )
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @subscriptions = Subscription.all
    respond_with(@subscriptions)
  end

  def show
    respond_with(@subscription)
  end

  def new
    @subscription = Subscription.new
    respond_with(@subscription)
  end

  def edit
  end

  def create
    @subscription = current_user.subscription.new(subscription_params)
    @subscription.save
    redirect_to edit_user_registration_path
    # respond_with(@subscription)
  end

  def update
    current_user.subscription.update(subscription_params)
    redirect_to edit_user_registration_path
  end

  def destroy
    @subscription.destroy
    respond_with(@subscription)
  end

  private
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    def subscription_params
      params.require(:subscription).permit(:new, :user_id, :ip_address, :first_name, :last_name, :card_type, :country, :city, :state, :postal_code, :years, :card_expires_on, :sub_years, :card_number, :card_verification)
    end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :card_type %><br>
    <%= f.select :card_type, [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]] %>
  </p> %>
  </div>
  <div class="field">
    <%= f.label :card_number %><br>
    <%= f.text_field :card_number %>
  </div>
  <div class="field">
    <%= f.label :card_verification, "(CVV)"%><br>
    <%= f.text_field :card_varification %>
  </div>
  <div class="field">
    <%= f.label :card_expires_on %><br>
    <%= f.date_select :card_expires_on, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :add_month_numbers => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>New</th>
      <th>User</th>
      <th>Ip address</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Card type</th>
      <th>Card expires on</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.new %></td>
        <td><%= subscription.user_id %></td>
        <td><%= subscription.ip_address %></td>
        <td><%= subscription.first_name %></td>
        <td><%= subscription.last_name %></td>
        <td><%= subscription.card_type %></td>
        <td><%= subscription.card_expires_on %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>New:</strong>
  <%= @subscription.new %>
</p>

<p>
  <strong>User:</strong>
  <%= @subscription.user_id %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @subscription.ip_address %>
</p>

<p>
  <strong>First name:</strong>
  <%= @subscription.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @subscription.last_name %>
</p>

<p>
  <strong>Card type:</strong>
  <%= @subscription.card_type %>
</p>

<p>
  <strong>Card expires on:</strong>
  <%= @subscription.card_expires_on %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>